apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q2yvyz980-python
  janus-idp.io/tekton: q2yvyz980-python
  backstage.io/kubernetes-id: q2yvyz980-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q2yvyz980-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
